# Generated by Django 5.1.4 on 2026-03-24 20:55

import django.db.models.deletion
import surveys.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating 1-5'), ('yes_no', 'Sí / No'), ('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('text', 'Texto abierto')], max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required_default', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_other_option', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('welcome_title', models.CharField(default='Tu opinión nos ayuda a mejorar', max_length=150)),
                ('welcome_text', models.TextField(default='Responde esta breve encuesta para calificar tu experiencia con Congente.')),
                ('closing_title', models.CharField(default='Gracias por compartir tu experiencia', max_length=150)),
                ('closing_text', models.TextField(default='Tus respuestas serán revisadas por el equipo de servicio al asociado.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QrEntryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('public_token', models.CharField(default=surveys.models.qr_token, max_length=80, unique=True)),
                ('allow_multiple_submissions', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_entry_points', to='surveys.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_entry_points', to='surveys.survey')),
            ],
            options={
                'ordering': ['area__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AreaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_questions', to='surveys.area')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_links', to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('preferred_channel', models.CharField(blank=True, max_length=150)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.area')),
                ('qr_entry_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.qrentrypoint')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.survey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('step_saved', 'Step saved'), ('submitted', 'Submitted'), ('blocked_duplicate', 'Blocked duplicate')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('qr_entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='surveys.qrentrypoint')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='surveys.surveysubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_answers', to='surveys.choiceoption')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='multiple_answers', to='surveys.choiceoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveysubmission')),
            ],
            options={
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='qrentrypoint',
            index=models.Index(fields=['public_token'], name='surveys_qre_public__ae458d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrentrypoint',
            index=models.Index(fields=['area', 'is_active'], name='surveys_qre_area_id_2686fd_idx'),
        ),
        migrations.AddIndex(
            model_name='areaquestion',
            index=models.Index(fields=['survey', 'area', 'order'], name='surveys_are_survey__3c6d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='areaquestion',
            index=models.Index(fields=['question'], name='surveys_are_questio_2ee22e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='areaquestion',
            unique_together={('survey', 'area', 'question')},
        ),
        migrations.AddIndex(
            model_name='surveysubmission',
            index=models.Index(fields=['area', 'created_at'], name='surveys_sur_area_id_4c09cb_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysubmission',
            index=models.Index(fields=['status', 'created_at'], name='surveys_sur_status_53479e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysubmission',
            index=models.Index(fields=['session_uuid'], name='surveys_sur_session_9f903d_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysubmission',
            index=models.Index(fields=['qr_entry_point', 'created_at'], name='surveys_sur_qr_entr_128ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionevent',
            index=models.Index(fields=['event_type', 'created_at'], name='surveys_sub_event_t_741cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='surveys_ans_questio_9e381c_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'question'], name='surveys_ans_submiss_84c03f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
