# Generated by Django 5.1.4 on 2026-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating 1-5'), ('yes_no', 'Si / No'), ('single_choice', 'Seleccion unica'), ('multiple_choice', 'Seleccion multiple'), ('text', 'Texto abierto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='closing_text',
            field=models.TextField(default='Tus respuestas seran revisadas por el equipo de servicio al asociado.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='welcome_title',
            field=models.CharField(default='Tu opinion nos ayuda a mejorar', max_length=150),
        ),
    ]
